using UnityEngine;

namespace EscapeWithYourFriends.World
{
    /// <summary>
    /// Every number and every colour the sky uses, in one text asset, for the same reason
    /// <see cref="IslandProfile"/> is one: the whole development loop is a terminal, and "make the
    /// nights darker" has to be an edit to a versioned file rather than an afternoon in the
    /// inspector.
    ///
    /// The gradients are keyed on time of day in 0..1, where 0 is midnight and 0.5 is noon. They are
    /// generated by <see cref="EditorTools.SkyFactory"/> rather than typed, because a Gradient in
    /// YAML is sixteen lines of packed key data that nobody can read or diff.
    /// </summary>
    [CreateAssetMenu(fileName = "DayNight", menuName = "EWYF/Day Night Profile")]
    public class DayNightProfile : ScriptableObject
    {
        [Header("Length")]
        [Tooltip("Minutes of real time for one full day and night. The acceptance criterion for #34 is that this is the only thing you have to change.")]
        public float CycleMinutes = 20f;

        [Tooltip("Where a fresh session starts, 0 to 1. 0.28 is mid-morning: you land in daylight and get one day to work out what is going on.")]
        public float StartOfDay = 0.28f;

        [Header("Sun")]
        [Tooltip("Compass direction the sun rises from, in degrees. Also the axis the moon runs along.")]
        public float SunAzimuth = -30f;

        [Tooltip("How far the sun's arc tilts off vertical. 0 puts it straight overhead at noon, which looks flat and casts no long shadows.")]
        public float SunTilt = 18f;

        [Tooltip("Sunlight colour over the day. Orange at the horizons, white at noon, unused underground.")]
        public Gradient SunColour = new Gradient();

        [Tooltip("Sunlight intensity over the day. Zero at night, where the moon takes over.")]
        public AnimationCurve SunIntensity = AnimationCurve.Linear(0f, 0f, 1f, 0f);

        [Header("Moon")]
        [Tooltip("Moonlight colour. Cold and blue, because that is the shorthand every player already understands.")]
        public Color MoonColour = new Color(0.55f, 0.66f, 0.95f);

        [Tooltip("Moonlight intensity. Deliberately low: the point of night is that a flashlight matters.")]
        public float MoonIntensity = 0.14f;

        [Tooltip("How hard moonlight shadows are. Soft and faint, or the night reads as a badly lit day.")]
        [Range(0f, 1f)] public float MoonShadowStrength = 0.35f;

        [Header("Ambient")]
        [Tooltip("Light from the sky itself, which is what fills every shadow. The single biggest lever on how dark night feels.")]
        public Gradient AmbientSky = new Gradient();

        [Tooltip("Light from the horizon.")]
        public Gradient AmbientEquator = new Gradient();

        [Tooltip("Light bounced off the ground.")]
        public Gradient AmbientGround = new Gradient();

        [Header("Fog and sky")]
        [Tooltip("Fog colour over the day. Matched to the sky, or the horizon shows a seam where the two meet.")]
        public Gradient FogColour = new Gradient();

        [Tooltip("Fog density over the day. Thicker at dawn and at night, which hides the draw distance and costs nothing.")]
        public AnimationCurve FogDensity = AnimationCurve.Linear(0f, 0.004f, 1f, 0.004f);

        [Tooltip("Skybox tint over the day.")]
        public Gradient SkyTint = new Gradient();

        [Tooltip("Skybox exposure over the day. This is what actually makes the night dark, rather than merely blue.")]
        public AnimationCurve SkyExposure = AnimationCurve.Linear(0f, 0.15f, 1f, 0.15f);

        [Tooltip("Atmosphere thickness over the day. High at the horizons scatters the light red.")]
        public AnimationCurve AtmosphereThickness = AnimationCurve.Linear(0f, 1f, 1f, 1f);

        /// <summary>Seconds in a full cycle. Clamped so a zero in the asset cannot divide by zero.</summary>
        public float CycleSeconds => Mathf.Max(10f, CycleMinutes * 60f);

        /// <summary>
        /// Where the sun is at this time of day. Noon points it straight down the tilt; midnight has
        /// it under the world, which is the cue for the moon to take over.
        /// </summary>
        public Quaternion SunRotation(float timeOfDay)
        {
            // -90 at midnight, 0 at sunrise, 90 at noon, 180 at sunset.
            float elevation = (timeOfDay - 0.25f) * 360f;
            return Quaternion.Euler(elevation, SunAzimuth, 0f) * Quaternion.Euler(0f, 0f, SunTilt);
        }

        /// <summary>How far above the horizon the sun is, -1 to 1. Negative is night.</summary>
        public float SunHeight(float timeOfDay) => Mathf.Sin((timeOfDay - 0.25f) * Mathf.PI * 2f);
    }
}
