using System.Collections.Generic;
using EscapeWithYourFriends.Combat;
using EscapeWithYourFriends.Net;
using UnityEngine;

namespace EscapeWithYourFriends.Player
{
    /// <summary>
    /// The walk cycle, written rather than imported (#77).
    ///
    /// The issue asked for a Mixamo set retargeted onto the rig. Mixamo needs a browser and an
    /// account, which this project's workflow does not have, and every alternative library either
    /// costs money or ships a humanoid rig that is not the one <c>PlayerPrefabBuilder</c> generates.
    /// So the animation is a function instead of an asset: eight bones, a sine wave, and the distance
    /// the body has travelled. It costs nothing, it needs no importer, no retarget and no
    /// <c>Animator</c>, and it cannot go out of date when the skeleton changes - it reads the rig's
    /// own rest pose at runtime and works from that.
    ///
    /// It is driven by distance, not by a clip playing at its own speed, so there is no foot sliding
    /// to tune: a sprinting body takes long fast strides and a crouched one takes short slow ones
    /// because both are the same wave sampled against metres walked. That is also why it needs no
    /// network traffic at all. Every client computes the same pose from a position it already has.
    ///
    /// **Not a component on the player prefab**, for the reasons in <see cref="Audio.Footsteps"/>:
    /// prefabs here are generated by editor scripts, and the movement runs inside a predicted tick
    /// that FishNet replays. One watcher outside the bodies avoids both.
    ///
    /// While a body is ragdolled the physics solver owns those transforms and this stays out of the
    /// way entirely - which is the half of #77's acceptance that actually had teeth.
    /// </summary>
    public class BodyAnimator : MonoBehaviour
    {
        /// <summary>Radians of gait per metre walked. Roughly one stride every 2 m.</summary>
        const float Cadence = 1.5f;

        /// <summary>Degrees the legs swing at a full run.</summary>
        const float Swing = 40f;

        /// <summary>Speed treated as a full run. Below it the whole pose scales down.</summary>
        const float Running = 5f;

        /// <summary>Vertical speed above which the feet are no longer involved.</summary>
        const float Airborne = 4f;

        static BodyAnimator _instance;

        readonly Dictionary<int, Rig> _rigs = new();

        /// <summary>Bodies posed this frame. The harness reads it; nothing else does.</summary>
        internal static int Posed { get; private set; }

        /// <summary>Bodies with a usable skeleton. The harness reads it.</summary>
        internal static int Tracked { get; private set; }

        internal static void Begin()
        {
            if (_instance != null) return;

            var go = new GameObject("BodyAnimator");
            DontDestroyOnLoad(go);
            _instance = go.AddComponent<BodyAnimator>();
        }

        /// <summary>One body's bones and where the rig left them.</summary>
        class Rig
        {
            internal Transform Root;
            internal RagdollController Ragdoll;
            internal CarrySystem Carry;

            internal Transform LegL, LegR, KneeL, KneeR, ArmL, ArmR;
            internal Quaternion RestLegL, RestLegR, RestKneeL, RestKneeR, RestArmL, RestArmR;

            internal Vector3 WasAt;
            internal float Speed;
            internal float Phase;
        }

        // LateUpdate, so a pose written here is the last word for the frame: movement, network
        // interpolation and the ragdoll's own restore have all already run.
        void LateUpdate()
        {
            Posed = 0;

            foreach (NetworkPlayerRegistry.PlayerBody body in NetworkPlayerRegistry.Players)
            {
                if (!body.IsValid) continue;

                int id = body.Object.ObjectId;

                if (!_rigs.TryGetValue(id, out Rig rig))
                {
                    rig = Build(body.Object.transform);
                    if (rig == null) continue;

                    _rigs[id] = rig;
                    Tracked = _rigs.Count;

                    Paint(body.Object.transform, id);
                }

                if (rig.Root == null) continue;

                Pose(rig);
            }
        }

        /// <summary>
        /// Finds the bones by the names <c>PlayerPrefabBuilder</c> gives them and remembers the pose
        /// they were built in. Everything below is expressed as an offset from that, so the rig can
        /// change proportions without touching this file.
        /// </summary>
        static Rig Build(Transform root)
        {
            var ragdoll = root.GetComponent<RagdollController>();
            if (ragdoll == null || ragdoll.HipBone == null) return null;

            Transform hips = ragdoll.HipBone;

            var rig = new Rig
            {
                Root = root,
                Ragdoll = ragdoll,
                Carry = root.GetComponent<CarrySystem>(),
                WasAt = root.position,

                LegL = Find(hips, "UpperLeg.L"),
                LegR = Find(hips, "UpperLeg.R"),
                KneeL = Find(hips, "LowerLeg.L"),
                KneeR = Find(hips, "LowerLeg.R"),
                ArmL = Find(hips, "UpperArm.L"),
                ArmR = Find(hips, "UpperArm.R"),
            };

            if (rig.LegL == null || rig.LegR == null || rig.ArmL == null || rig.ArmR == null)
            {
                Debug.LogWarning($"[BodyAnimator] {root.name} has no recognisable legs; leaving it alone.");
                return null;
            }

            rig.RestLegL = rig.LegL.localRotation;
            rig.RestLegR = rig.LegR.localRotation;
            rig.RestKneeL = rig.KneeL != null ? rig.KneeL.localRotation : Quaternion.identity;
            rig.RestKneeR = rig.KneeR != null ? rig.KneeR.localRotation : Quaternion.identity;
            rig.RestArmL = rig.ArmL.localRotation;
            rig.RestArmR = rig.ArmR.localRotation;

            return rig;
        }

        /// <summary>
        /// Four grey bodies are four identical bodies, and a co-op game where you cannot tell which
        /// one is you is a co-op game nobody can play (#76). So each body's cloth is tinted the first
        /// time it is seen.
        ///
        /// Through a <see cref="MaterialPropertyBlock"/> rather than a material, because a material
        /// per player is four materials, four draw calls and four assets that the palette pass would
        /// then have to know about. A property block is per renderer, costs nothing and still batches.
        /// Only the cloth is tinted: recolouring skin gives four aliens.
        /// </summary>
        static void Paint(Transform root, int id)
        {
            Color[] shirts =
            {
                new(0.78f, 0.26f, 0.22f), new(0.24f, 0.44f, 0.76f),
                new(0.86f, 0.72f, 0.22f), new(0.30f, 0.62f, 0.34f),
            };

            Color shirt = shirts[Mathf.Abs(id) % shirts.Length];
            var block = new MaterialPropertyBlock();

            foreach (Renderer renderer in root.GetComponentsInChildren<Renderer>(includeInactive: true))
            {
                Material worn = renderer.sharedMaterial;
                if (worn == null || !worn.name.StartsWith("Cloth")) continue;

                renderer.GetPropertyBlock(block);
                block.SetColor("_BaseColor", shirt);
                block.SetColor("_Color", shirt);
                renderer.SetPropertyBlock(block);
            }
        }

        static Transform Find(Transform hips, string bone)
        {
            foreach (Transform t in hips.GetComponentsInChildren<Transform>(includeInactive: true))
                if (t.name == bone) return t;

            return null;
        }

        static void Pose(Rig rig)
        {
            // A ragdoll is the physics solver's pose. Writing over it is how you get a corpse that
            // twitches at the hips while the rest of it lies still.
            if (rig.Ragdoll != null && rig.Ragdoll.IsRagdolled)
            {
                rig.WasAt = rig.Root.position;
                rig.Speed = 0f;
                return;
            }

            float dt = Mathf.Max(Time.deltaTime, 0.0001f);
            Vector3 moved = rig.Root.position - rig.WasAt;
            rig.WasAt = rig.Root.position;

            bool falling = Mathf.Abs(moved.y / dt) > Airborne;

            moved.y = 0f;

            // Smoothed, because one frame of network interpolation arriving late should not make a
            // body break into a sprint and back.
            rig.Speed = Mathf.Lerp(rig.Speed, moved.magnitude / dt, 1f - Mathf.Exp(-8f * dt));
            rig.Phase += rig.Speed * Cadence * dt;

            if (falling)
            {
                // Legs up, arms out. Nobody falls elegantly and nobody should.
                Set(rig.LegL, rig.RestLegL, -30f);
                Set(rig.LegR, rig.RestLegR, -30f);
                Set(rig.KneeL, rig.RestKneeL, 55f);
                Set(rig.KneeR, rig.RestKneeR, 55f);
                Set(rig.ArmL, rig.RestArmL, -70f);
                Set(rig.ArmR, rig.RestArmR, -70f);

                Posed++;
                return;
            }

            float gait = Mathf.Clamp01(rig.Speed / Running);
            float swing = Swing * gait;
            float wave = Mathf.Sin(rig.Phase);

            Set(rig.LegL, rig.RestLegL, -swing * wave);
            Set(rig.LegR, rig.RestLegR, swing * wave);

            // A knee only bends one way. Half a wave each, offset, so each leg folds as it comes
            // through and stays straight as it takes the weight.
            Set(rig.KneeL, rig.RestKneeL, Mathf.Max(0f, wave) * swing * 0.8f);
            Set(rig.KneeR, rig.RestKneeR, Mathf.Max(0f, -wave) * swing * 0.8f);

            if (rig.Carry != null && rig.Carry.IsCarrying)
            {
                // Both arms forward and level: whatever is being carried is in front of the chest,
                // and arms swinging through it looks like a bug rather than like a person.
                Set(rig.ArmL, rig.RestArmL, -75f);
                Set(rig.ArmR, rig.RestArmR, -75f);
            }
            else
            {
                // Opposite arm to leg, and less of it. This is the single detail that makes a walk
                // read as a walk.
                Set(rig.ArmL, rig.RestArmL, swing * 0.6f * wave);
                Set(rig.ArmR, rig.RestArmR, -swing * 0.6f * wave);
            }

            // No idle sway on the chest, however much a mannequin it leaves. The head is a child of
            // the chest and the camera rig rides the head, so two degrees of breathing is two degrees
            // of camera rocking at every moment the player is standing still and reading the world.

            Posed++;
        }

        static void Set(Transform bone, Quaternion rest, float pitch)
        {
            if (bone == null) return;

            bone.localRotation = rest * Quaternion.Euler(pitch, 0f, 0f);
        }
    }
}
