using EscapeWithYourFriends.Core;
using UnityEngine;
using UnityEngine.InputSystem;

namespace EscapeWithYourFriends.Player
{
    /// <summary>
    /// Turns devices into the handful of values the rest of the player cares about.
    ///
    /// Named Reader rather than PlayerInput so it cannot be confused with the Input System component
    /// of that name, which this deliberately does not use: that component drives behaviour through
    /// UnityEvents and SendMessage, and every one of those fires on the frame the device changed.
    /// Prediction needs input sampled by the tick, not by the frame, so this class polls instead and
    /// buffers the one-shot presses that happen between two ticks.
    ///
    /// Only the owner ever binds. A body you do not control has this component sitting inert, which
    /// keeps four bodies in one process from all reading the same keyboard during a local test.
    /// </summary>
    public class PlayerInputReader : MonoBehaviour
    {
        [Header("Actions")]
        [Tooltip("Generated by InputAssetBuilder. Must contain a Player map.")]
        [SerializeField] InputActionAsset _actions;

        [Header("Look")]
        [Tooltip("Degrees of turn per unit of mouse delta.")]
        [SerializeField] float _lookSensitivity = 0.08f;

        [SerializeField] float _minPitch = -85f;
        [SerializeField] float _maxPitch = 85f;

        [Tooltip("Lock and hide the cursor while this body is being controlled.")]
        [SerializeField] bool _lockCursor = true;

        [Header("Automation")]
        [Tooltip("Drive this body from a fixed pattern instead of devices. Also set by -botMove.")]
        [SerializeField] bool _scriptedInput;

        InputActionAsset _instance;
        InputActionMap _map;

        InputAction _move, _look, _jump, _sprint, _crouch, _interact, _attack, _altAttack, _drop;
        InputAction _hotbarScroll;
        readonly InputAction[] _hotbar = new InputAction[Items.Inventory.HotbarSlots];

        bool _bound;
        bool _scripted;
        float _scriptStart;

        // One-shot presses, buffered until whoever cares consumes them. A key tapped between two
        // ticks would otherwise be dropped entirely: at 30Hz that is a third of a second of taps.
        bool _jumpQueued, _interactQueued, _attackQueued, _altAttackQueued, _dropQueued;

        // Hotbar selection is two inputs for one value. -1 means no number key was pressed; the
        // scroll accumulates because a flick of the wheel is several notches inside one frame.
        int _hotbarQueued = -1;
        int _hotbarSteps;
        float _scrollRemainder;

        /// <summary>Movement axis, -1..1 per component. Y is forward.</summary>
        public Vector2 Move { get; private set; }

        /// <summary>Where the body faces, in degrees. The motor replicates this.</summary>
        public float Yaw { get; private set; }

        /// <summary>Where the camera looks vertically, in degrees. Never replicated — see #17.</summary>
        public float Pitch { get; private set; }

        public bool Sprint { get; private set; }

        public bool Crouch { get; private set; }

        /// <summary>
        /// Interact held down right now, as opposed to the buffered press. Rescuing a downed
        /// teammate (#105) is the first verb in the game that is a hold rather than a tap, and a
        /// buffered press cannot express "still holding" — by the time the buffer is read the key
        /// may already be back up.
        /// </summary>
        public bool InteractHeld { get; private set; }

        /// <summary>
        /// Drop held down right now. The same reason as <see cref="InteractHeld"/>, for the opposite
        /// gesture: the drop key is a tap to drop and a hold to throw (see <c>ItemDropper</c>), and
        /// the difference is only visible while the key is still down.
        /// </summary>
        public bool DropHeld { get; private set; }

        /// <summary>True while this reader is driving a body, i.e. we own it.</summary>
        public bool IsBound => _bound;

        /// <summary>
        /// Starts reading devices. Called by the motor once it knows this body is ours.
        /// </summary>
        public void Bind(float startYaw)
        {
            if (_bound) return;

            if (_actions == null)
            {
                Debug.LogError("[PlayerInputReader] No action asset assigned; this player cannot move.");
                return;
            }

            // A headless build has no devices at all, so a smoke test that only checked for silence
            // would pass on a motor that never ran. ReadScripted actually moves the body.
            _scripted = _scriptedInput || CommandLine.HasFlag("-botMove");
            _scriptStart = Time.time;

            // A clone per player. Action assets carry their own enabled state and action callbacks, so
            // two bodies sharing one instance would fight over it the moment a second local player
            // exists — and disabling one would silently disable the other.
            _instance = Instantiate(_actions);
            _map = _instance.FindActionMap("Player", throwIfNotFound: true);

            _move = _map.FindAction("Move", throwIfNotFound: true);
            _look = _map.FindAction("Look", throwIfNotFound: true);
            _jump = _map.FindAction("Jump", throwIfNotFound: true);
            _sprint = _map.FindAction("Sprint", throwIfNotFound: true);
            _crouch = _map.FindAction("Crouch", throwIfNotFound: true);
            _interact = _map.FindAction("Interact", throwIfNotFound: true);
            _attack = _map.FindAction("Attack", throwIfNotFound: true);
            _altAttack = _map.FindAction("AltAttack", throwIfNotFound: true);
            _drop = _map.FindAction("Drop", throwIfNotFound: true);

            // Optional, so an action asset generated before #42 still binds everything else rather
            // than throwing and leaving the player unable to move at all.
            _hotbarScroll = _map.FindAction("HotbarScroll", throwIfNotFound: false);
            for (int i = 0; i < _hotbar.Length; i++)
                _hotbar[i] = _map.FindAction($"Hotbar{i + 1}", throwIfNotFound: false);

            _map.Enable();

            Yaw = startYaw;
            Pitch = 0f;
            _bound = true;

            ApplyCursorLock(true);
        }

        /// <summary>Stops reading devices. Called when the body despawns or stops being ours.</summary>
        public void Release()
        {
            if (!_bound) return;

            _map.Disable();
            Destroy(_instance);

            _instance = null;
            _map = null;
            _bound = false;

            Move = Vector2.zero;
            Sprint = Crouch = false;
            ClearQueued();

            ApplyCursorLock(false);
        }

        void OnDisable() => Release();

        void Update()
        {
            if (!_bound) return;

            if (_scripted)
            {
                ReadScripted();
                return;
            }

            Move = Vector2.ClampMagnitude(_move.ReadValue<Vector2>(), 1f);
            Sprint = _sprint.IsPressed();
            Crouch = _crouch.IsPressed();
            InteractHeld = _interact.IsPressed();
            DropHeld = _drop.IsPressed();

            Vector2 look = _look.ReadValue<Vector2>();
            Yaw = Mathf.Repeat(Yaw + look.x * _lookSensitivity, 360f);
            Pitch = Mathf.Clamp(Pitch - look.y * _lookSensitivity, _minPitch, _maxPitch);

            // OR into the buffer instead of overwriting: several frames can pass between ticks, and
            // only one of them saw the press.
            _jumpQueued |= _jump.WasPressedThisFrame();
            _interactQueued |= _interact.WasPressedThisFrame();
            _attackQueued |= _attack.WasPressedThisFrame();
            _altAttackQueued |= _altAttack.WasPressedThisFrame();
            _dropQueued |= _drop.WasPressedThisFrame();

            ReadHotbar();
        }

        /// <summary>
        /// Number keys pick a slot outright; the wheel steps through them. Both are buffered like the
        /// presses above, because selection is sent to the server and a notch that fell between two
        /// ticks would be a slot the player chose and never got.
        /// </summary>
        void ReadHotbar()
        {
            for (int i = 0; i < _hotbar.Length; i++)
                if (_hotbar[i] != null && _hotbar[i].WasPressedThisFrame())
                    _hotbarQueued = i;

            if (_hotbarScroll == null) return;

            // A wheel reports 120 per notch on Windows and 1 elsewhere, so normalise by sign and keep
            // the remainder: a trackpad sends a stream of fractions that would otherwise never move.
            float raw = _hotbarScroll.ReadValue<float>();
            if (Mathf.Abs(raw) < 0.01f) return;

            _scrollRemainder += Mathf.Abs(raw) > 10f ? raw / 120f : raw;

            int steps = (int)_scrollRemainder;
            if (steps == 0) return;

            _scrollRemainder -= steps;

            // Wheel up is the previous slot, which is what every game with a hotbar does.
            _hotbarSteps -= steps;
        }

        /// <summary>
        /// A fixed lap: walk forward, turn steadily, sprint for half of every cycle, crouch for a
        /// slice of it, and jump twice a cycle. Every branch the motor has is exercised, and because
        /// the body keeps turning it also covers moving in a direction that is not the one it started
        /// facing — which is where a yaw that failed to replicate would show up.
        ///
        /// The turn rate is what keeps the lap on the platform. Circle radius is speed over turn
        /// rate: at the sprint speed of 7.5 m/s, 60 degrees per second gives about 7 metres, so four
        /// bots on a 4-metre spawn ring stay well inside the 50-metre greybox floor. Turn slower and
        /// they walk off the edge and fall for the rest of the test, which reads as a movement bug
        /// and is not one.
        ///
        /// The bots also brawl. Four bodies circling a 4-metre ring are inside each other's reach, so
        /// swinging on a timer means the run ends up exercising melee, stun, ragdoll and the shock
        /// shake without anyone touching a keyboard. Without it a headless test only ever sees a
        /// character standing upright, which is exactly the case the camera handles well.
        /// </summary>
        void ReadScripted()
        {
            float t = Time.time - _scriptStart;
            const float cycle = 8f;
            float phase = Mathf.Repeat(t, cycle) / cycle;

            Move = new Vector2(Mathf.Sin(t * 0.7f) * 0.5f, 1f);
            Yaw = Mathf.Repeat(t * 60f, 360f);
            Sprint = phase < 0.5f;
            Crouch = phase > 0.75f && phase < 0.9f;

            // Bots never let go. A scripted lap has no way to aim at a downed friend, so the hold
            // is worth nothing on its own — but leaving it false would mean a bot that somehow did
            // start a rescue cancelled it on the very next frame, which is a confusing way for an
            // unrelated test to fail.
            InteractHeld = true;

            _jumpQueued |= Mathf.Repeat(t, 4f) < Time.deltaTime;
            _attackQueued |= Mathf.Repeat(t, 1.5f) < Time.deltaTime;

            // Offset so the taser never fires on the same frame as a punch, which would make a failure
            // in one look like a failure in the other.
            _altAttackQueued |= Mathf.Repeat(t + 3f, 7f) < Time.deltaTime;
        }

        /// <summary>Reads and clears the buffered jump. Called once per tick by the motor.</summary>
        public bool ConsumeJump() => Consume(ref _jumpQueued);

        public bool ConsumeInteract() => Consume(ref _interactQueued);

        public bool ConsumeAttack() => Consume(ref _attackQueued);

        public bool ConsumeAltAttack() => Consume(ref _altAttackQueued);

        public bool ConsumeDrop() => Consume(ref _dropQueued);

        /// <summary>The hotbar slot a number key asked for, or -1. Cleared by reading.</summary>
        public int ConsumeHotbarSlot()
        {
            int slot = _hotbarQueued;
            _hotbarQueued = -1;
            return slot;
        }

        /// <summary>How many slots the wheel moved since the last read, signed. Cleared by reading.</summary>
        public int ConsumeHotbarSteps()
        {
            int steps = _hotbarSteps;
            _hotbarSteps = 0;
            return steps;
        }

        static bool Consume(ref bool flag)
        {
            if (!flag) return false;
            flag = false;
            return true;
        }

        void ClearQueued()
        {
            _jumpQueued = _interactQueued = _attackQueued = _altAttackQueued = _dropQueued = false;
            _hotbarQueued = -1;
            _hotbarSteps = 0;
            _scrollRemainder = 0f;
        }

        void ApplyCursorLock(bool locked)
        {
            // A headless smoke-test build has no cursor to lock, and touching it there is noise.
            if (!_lockCursor || Application.isBatchMode) return;

            Cursor.lockState = locked ? CursorLockMode.Locked : CursorLockMode.None;
            Cursor.visible = !locked;
        }
    }
}
